# Generated by Django 4.1.4 on 2023-04-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoChirho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chirho', models.CharField(max_length=50)),
                ('comision_chirho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntregableChirho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chirho', models.CharField(max_length=50)),
                ('fecha_chirho', models.DateField()),
                ('entregado_chirho', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteChirho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chirho', models.CharField(max_length=50)),
                ('apellido_chirho', models.CharField(max_length=50)),
                ('email_chirho', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorChirho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chirho', models.CharField(max_length=50)),
                ('apellido_chirho', models.CharField(max_length=50)),
                ('email_chirho', models.EmailField(max_length=254)),
                ('prefesion_chirho', models.CharField(max_length=50)),
            ],
        ),
    ]
